version: 2.1

orbs:
  maven: circleci/maven@1.4.1

parameters:
  maven_version: 
    default: "3.9.2"
    type: string

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.10
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          name: restore maven cache
          keys: 
            - v1-{{ checksum "pom.xml" }}
            - v1-
      - run: 
          name: package the app
          command: mvn compile
      - save_cache:
          paths:
            - ../.m2
          key: v1-{{ checksum "pom.xml" }}

workflows:
  build-and-test:
    jobs:
      - build
      - maven/test:
          requires:
            - build